project_name: "HousingList"
baseline: "Organize housings for groups, the easy way"
description: "Nomad workers, families, or groups of friends are using HousingList to easily organize together their trip, especially the housing searching process."
twitter: "@JoinHousingList"
